### PR TITLE
[WIP] Feature/embed mode ui style

### PR DESCRIPTION
**Pull request by nerik**
Adds styling to the embed mode UI

### CODE REVIEW

**Comment by vectorsize** [comment]
I added styling for the top-bar on embed, you want to take a look @nerik ? The styling should be ready.

**Comment by nerik** [comment]
Code looks good as it is 👍 
There are two issues though:
- the default style has been altered somehow, compare this version with the production one:

screen shot 2017-07-11 at 15 07 56

screen shot 2017-07-11 at 15 08 07

- not actually related to this PR, more something we overlooked for now: using the buttons in embed mode removes the theme part of the URL and thus interacting with them reverts to the default style:
screen shot 2017-07-11 at 15 10 34

**Comment by vectorsize** [comment]
Regarding broken default styles, that's my bad, I cross checked were possible but must have missed something.
Regarding the url update upon clicking the buttons, I had fixed that in the past, might be a regression, but it should definitely keep the theme in the url.

Ill fix that @nerik thanks

**Comment by vectorsize** [comment]
Non embed mode styles are fixed now, brought back the css definitions.

**Pull request merged**
